# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Edward Huang | Software Engineer
name: Edward Huang
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to Edward Huang's Personal Website. I am not your typical software engineer..
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.edward-huang.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username: edwardGunawan

# google analytics
google_analytics: UA-113368564-1

# Build settings
markdown: kramdown

# Include the file from pages
include: ['_pages']

# Create pretty permanent link
permalink: pretty

# create sass css style-page
sass:
  sass_dir: _sass
  style: compressed

# set frontmatter values through defaults
defaults:
  - scope:
      path: assets/img
    values: # set the front-matter variable in the static file
      image: true # look for jekyll assets img site
    # setting front-matter for project image
  - scope:
      path: assets/custom_js
    values:
      customJS: true
  - scope:
      path: assets/img/Portfolio.JPG
    values:
      title: Portfolio
      backgroundColor: ece9e6
      link: /v1/
      description: First iteration portfolio. Designed and developed with a concious effort avoid using any framework.
  - scope:
      path: assets/img/TimerApp.JPG
    values:
      title: Timer-app
      backgroundColor: hsl(0, 0%, 100%)
      link: https://github.com/edwardGunawan/ReactTimerApp
      description: Timer app provides timer. Designed using react to create modular layout and liquid codebase.
  - scope:
      path: assets/img/TrackMe.JPG
    values:
      title: TrackMe
      backgroundColor: hsl(0, 0%, 100%)
      link: https://github.com/edwardGunawan/TrackMe
      description: React application of helping re-arranging your todo list.
  - scope:
      path: assets/img/MoocSearch.JPG
    values:
      title: MoocSearch
      backgroundColor: hsl(0, 0%, 100%)
      link: https://github.com/edwardGunawan/mooc_search
      description: Search Engine for Online Courses from Udemy, Udacity, and Iversity.



exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - "README.md"
  - "build"

keepfiles:
  - "CNAME"
  - ".git"
  - ".gitignore"

# jekyll plugins
plugins:
  - jekyll-sitemap
  - jekyll-minifier
